### ISSUE TITLE
What is the final purpose of this parser

### ISSUE THREAD

**Issue by asmwarrior** [robertoraggi/cplusplus#15]
I know this project started several years ago, and after that, it just halted for several years. And I see you have resumed the develop again in recent months. First, I'd like to say, good work!

Now, here comes my question, what does the final purpose of this parser. Will it support some features like Clang, for example, code completion, find declaration or find implementation. 

If I remember correctly, you are the original author of the parser in QTCreator/Kdevelope, but now those IDEs all switches to use Clang based parser.

Thanks.

**Comment by robertoraggi** [comment]
Hey @asmwarrior, thanks for showing your interest in this project. I really don’t have big plans for this code base, it’s just a hobby project. That said, my goal is to implement a toy compiler for c++2a.
